### ISSUE TITLE
Browser console errors thrown on "Burn" page

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/staking#138]
**Description:**
Two types of errors are thrown in browser console on "Burn" page:
- `Invalid ENS name`
- `Duplicate definition`

**Reproduction steps:**
1. Go to Staking website, "Burn" page (https://dev.staking.synthetix.io/staking/burn)
2. Look at browser console

**Expected result:**
- No errors thrown

**Environment:**
MacBook Pro 15,4-inch (2880 x 1800), macOS 11.1, Chrome 87.0.4280.88

**Screenshots / videos:**
<img width="1670" alt="Screenshot 2020-12-17 at 22 34 28" src="https://user-images.githubusercontent.com/8177587/102546686-4aeae400-40b8-11eb-9199-8de1e30084e0.png">

**Comment by evgenyboxer** [comment]
Still happens?

**Comment by andytcf** [comment]
Closing because stale
