### ISSUE TITLE
Unnecessary scrollbars inside vesting section on "Escrow" page

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/staking#139]
**Description:**
There are unnecessary scrollbars visible inside vesting section on "Escrow" page.

**Reproduction steps:**
1. Go to Staking website, "Escrow" page (https://dev.staking.synthetix.io/escrow)

**Expected result:**
- No scrollbars shown

**Environment:**
MacBook Pro 15,4-inch (2880 x 1800), macOS 11.1, Chrome 87.0.4280.88

**Screenshots / videos:**
<img width="507" alt="Screenshot 2020-12-17 at 22 43 51" src="https://user-images.githubusercontent.com/8177587/102547346-5d195200-40b9-11eb-9eb8-c5be11a34976.png">
<img width="491" alt="Screenshot 2020-12-17 at 22 43 49" src="https://user-images.githubusercontent.com/8177587/102547349-5e4a7f00-40b9-11eb-82a4-1b82637b04b3.png">

**Comment by evgenyboxer** [comment]
Still happens? Can't reproduce now.
