### ISSUE TITLE
css file is not used because of "request credentials mode does not match" console warning

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/staking#140]
**Description:**
Following error is thrown while navigating through staking left menu:
```
A preload for 'https://dev.staking.synthetix.io/_next/static/css/9be82a939a0e4a9c1536.css' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.
```
It results in some css file being loaded however not used.

**Reproduction steps:**
1. Go to Staking website (https://dev.staking.synthetix.io/)
2. Navigate through left menu over several pages

**Expected result:**
- No warning thrown

**Environment:**
MacBook Pro 15,4-inch (2880 x 1800), macOS 11.1, Chrome 87.0.4280.88

**Screenshots / videos:**
<img width="1655" alt="Screenshot 2020-12-17 at 22 55 29" src="https://user-images.githubusercontent.com/8177587/102550510-3b6e9980-40be-11eb-9c69-f6e0716f7a51.png">

**Comment by evgenyboxer** [comment]
Still happens?

**Comment by andytcf** [comment]
Closing because stale
