### ISSUE TITLE
"undefined" notification while claiming staked SNX

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/staking#179]
**Description:**
After claiming my rewards (SNX) from staking, I've got two notifications, one regarding pending transaction and another one saying "undefined".

**Prerequisites:**
- Metamask wallet
- Staked SNX

**Reproduction steps:**
1. Go to Staking website, "Earn" page (https://dev.staking.synthetix.io/earn/claim)
2. Connect your wallet
3. Go to SNX staking pool
4. Claim your reward

**Expected result:**
- "undefined" notification shouldn't show up

**Environment:**
MacBook Pro 15,4-inch (2880 x 1800), macOS 11.1, Chrome 87.0.4280.88

**Screenshots / videos:**
<img width="286" alt="Screenshot 2020-12-22 at 00 50 09" src="https://user-images.githubusercontent.com/8177587/102832802-bc47d100-43ef-11eb-8024-0df5926205d2.png">

**Comment by evgenyboxer** [comment]
Couldn't reproduce
