### ISSUE TITLE
Staking stats disappear from left menu if browser window is too small

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/staking#212]
**Description:**
Staking stats disappear from left menu if browser window is too small.

**Reproduction steps:**
1. Go to Staking website, "Earn" page (https://dev.staking.synthetix.io/)
2. Resize your browser window to smaller

**Expected result:**
- Show a scrollbar inside menu "stats" section instead of hiding it?

**Environment:**
MacBook Pro 15,4-inch (2880 x 1800), macOS 11.1, Chrome 87.0.4280.88

**Screenshots / videos:**
![2021-01-03 14 37 20](https://user-images.githubusercontent.com/8177587/103479947-68ff5680-4dd1-11eb-954e-fe9dc07dea45.gif)

**Comment by evgenyboxer** [comment]
This was done intentionally and will be resolved when we got responsive designs.
