### ISSUE TITLE
"SNX" pool shows 0% APR on "Earn" page

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/staking#213]
**Description:**
"SNX" pool shows 0% APR on "Earn" page

**Prerequisites:**
- Metamask wallet

**Reproduction steps:**
1. Go to Staking website, "Earn" page (https://dev.staking.synthetix.io/)
2. Connect your wallet

**Expected result:**
- Show proper "SNX" pool APR

**Environment:**
MacBook Pro 15,4-inch (2880 x 1800), macOS 11.1, Chrome 87.0.4280.88

**Screenshots / videos:**
<img width="1666" alt="Screenshot 2021-01-03 at 14 40 13" src="https://user-images.githubusercontent.com/8177587/103479969-9946f500-4dd1-11eb-870a-e2fb8cf85139.png">

**Comment by evgenyboxer** [comment]
can you reproduce? I'm seeing correct APR.

**Comment by evgenyboxer** [comment]
this is fixed
