### ISSUE TITLE
Global notification banner

### ISSUE THREAD

**Issue by andytcf** [Synthetixio/staking#264]
There needs to be a banner that is accessible and viewed globally within the staking app to show messages to the user.

This will support
- Vote notifications (telling a user to vote, i.e there's a proposal that needs to be voted on)
- Liquidation warning (when a user has gone at or below 200% c-ratio)

## Requirements

- [x] Design (https://www.figma.com/file/M58E2cxkOgTPWMHRX7FTna/Staking-User-Flows?node-id=1986%3A2669) 
- [x] Development

**Comment by zoe-archer** [comment]
Proposed UI for global notification banners: 

<img width="1152" alt="notifications-alert" src="https://user-images.githubusercontent.com/46664538/107177092-198df500-6a25-11eb-9a82-a6419aa4bd40.png">
<img width="1152" alt="notifications-warning" src="https://user-images.githubusercontent.com/46664538/107177098-1bf04f00-6a25-11eb-9d01-39e5dec048bf.png">

Designs found here: 
https://www.figma.com/file/M58E2cxkOgTPWMHRX7FTna/Staking-User-Flows?node-id=1873%3A0
