### ISSUE TITLE
Going straight to /earn/claim resolves an illegible error

### ISSUE THREAD

**Issue by andytcf** [Synthetixio/staking#295]
When visiting the /earn/claim url it throws an error that is really long and obfuscated

![image](https://user-images.githubusercontent.com/39738607/106698578-2aa9c100-6635-11eb-947b-591079f40241.png)

**Comment by evgenyboxer** [comment]
@andytcf is there a way to reproduce? tried it, seems to work fine.

Adding @drptbl here, perhaps he can help to reproduce too

**Comment by drptbl** [comment]
> @andytcf is there a way to reproduce? tried it, seems to work fine.
> 
> Adding @drptbl here, perhaps he can help to reproduce too

@evgenyboxer Tried to reproduce by going to https://staking.synthetix.io/earn/claim and then connecting a wallet. Couldn't see an error.
