### ISSUE TITLE
Delegate management mode

### ISSUE THREAD

**Issue by zoe-archer** [Synthetixio/staking#311]
Add Delegate section to wallet modal:

- list of delegates
- add a delegate
- remove a delegate

Also add the ability to approve certain functions (MVP = approve / remove all) 

@clementbalestrat ready for development

@ajsantander to manually verify

**Comment by zoe-archer** [comment]
Proposed UI:

<img width="1152" alt="delegate-1" src="https://user-images.githubusercontent.com/46664538/107903115-7ac14580-6f9c-11eb-8e28-209913d78923.png">
<img width="1152" alt="delegate-2" src="https://user-images.githubusercontent.com/46664538/107903121-7d239f80-6f9c-11eb-978d-6f78f9c918cd.png">
<img width="1152" alt="delegate-3" src="https://user-images.githubusercontent.com/46664538/107903128-801e9000-6f9c-11eb-9490-6ffef22e867e.png">
<img width="1152" alt="delegate-4" src="https://user-images.githubusercontent.com/46664538/107903139-857bda80-6f9c-11eb-806c-d58cb5921473.png">
<img width="1152" alt="delegate-5" src="https://user-images.githubusercontent.com/46664538/107903142-87459e00-6f9c-11eb-9a01-0d90e01682cf.png">
<img width="1152" alt="delegate-6" src="https://user-images.githubusercontent.com/46664538/107903147-8ad92500-6f9c-11eb-8a09-4bfb3fdbe6e4.png">
<img width="1152" alt="delegate-7" src="https://user-images.githubusercontent.com/46664538/107903151-8d3b7f00-6f9c-11eb-9cc6-119c49c2b808.png">


Figma designs here: https://www.figma.com/file/M58E2cxkOgTPWMHRX7FTna/Staking-User-Flows?node-id=1986%3A2922

**Comment by vbstreetz** [comment]
And is this different from https://github.com/Synthetixio/staking/issues/267 ?

**Comment by andytcf** [comment]
> Hey @andytcf, could you be knowing what contract we are working with here?
> `DelegateApprovals#approveAllDelegatePowers` and `DelegateApprovals#removeAllDelegatePowers`? https://etherscan.io/address/0x15fd6e554874B9e70F832Ed37f231Ac5E142362f#writeContract

This is correct, https://etherscan.io/address/0x15fd6e554874B9e70F832Ed37f231Ac5E142362f. This PR/issue is the first version of the full-version. This issue just allows for adding and removing ALL delegate powers at a time so the functions you quoted are correct. 

Yeah it is different, issue #267 is both the delegate mode and also the improvements that allow the delegate to actually mint, claim, burn.

**Comment by vbstreetz** [comment]
<img width="813" alt="Screenshot 2021-03-11 at 04 27 38" src="https://user-images.githubusercontent.com/60554509/110721757-2f5c2900-8222-11eb-8863-622c46f08c4e.png">

@andytcf I actually implemented the full _set_. @zoe-archer Should we shift the action input editor? ☝🏽

**Comment by andytcf** [comment]
@vbstreetz can we move this issue to your TZ board? Thank you

**Comment by unstylo** [comment]
> @vbstreetz can we move this issue to your TZ board? Thank you

Awesome.

**Comment by vbstreetz** [comment]
Moved to https://github.com/orgs/Synthetixio/projects/4
