### ISSUE TITLE
DESIGN: mobile responsive version of the Staking dApp

### ISSUE THREAD

**Issue by andytcf** [Synthetixio/staking#335]
## Required mobile responsive components/flows: 

- [ ] The navigation bar
- [ ] The wallet connection dropdown / menu
- [ ] The settings dropdown/menu
- [ ] Stat boxes (currently at the top of the screen (c-ratio, active debt etc)) 
- [ ] The user wallet stats (currently bottom left of the screen) 
- [ ] All the pages and user flows (e.g. Debt page, Mint & Burn page (+ all the flows (e.g. Mint Max...)))

**Comment by zoe-archer** [comment]
Figma file found here: 
https://www.figma.com/file/Z5O65qcEXk8FAW5NBtznWu/Mobile-Staking-UX?node-id=1%3A2

**Comment by erikatruscott-ux** [comment]
Complete sections, with all states, ready for review:

**Home:**
https://www.figma.com/file/maCDRPNi3ewRnhHGe2togk/Staking-Mobile?node-id=4%3A5

**Mint & Burn:**
https://www.figma.com/file/maCDRPNi3ewRnhHGe2togk/Staking-Mobile?node-id=177%3A163436

**Earn:**
https://www.figma.com/file/maCDRPNi3ewRnhHGe2togk/Staking-Mobile?node-id=181%3A86436

**Debt**
https://www.figma.com/file/maCDRPNi3ewRnhHGe2togk/Staking-Mobile?node-id=210%3A310077

--------------------------------------------------------------

All components created for the above designs
https://www.figma.com/file/maCDRPNi3ewRnhHGe2togk/Staking-Mobile?node-id=4%3A4

--------------------------------------------------------------
**Prototype:** 
Revealing stats on Tablet. (The same would apply to mobile)
https://www.figma.com/proto/maCDRPNi3ewRnhHGe2togk/Staking-Mobile?node-id=169%3A90565&viewport=-2614%2C3590%2C0.3221738040447235&scaling=scale-down&page-id=4%3A5

--------------------------------------------------------------

Outstanding sections

- Loans
- Governance
- Layer 2
- Escrow
- Synths
- History
- Delegate
- Menus
