### ISSUE TITLE
Clear Debt

### ISSUE THREAD

**Issue by andytcf** [Synthetixio/staking#341]
~todo add info

**Comment by zoe-archer** [comment]
Proposed 'Clear Debt' flows found here:

**Standard flow:** 
https://www.figma.com/file/M58E2cxkOgTPWMHRX7FTna/Staking-User-Flows?node-id=2414%3A2

**Not enough sUSD (1Inch integration):**
https://www.figma.com/file/M58E2cxkOgTPWMHRX7FTna/Staking-User-Flows?node-id=2414%3A1091
