### ISSUE TITLE
Unable to switch to L2 network when wallet is not connected

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/staking#419]
**Description:**
Unable to switch to L2 network when wallet is not connected.

**Prerequisites:**
- connected to L1 mainnet in metamask
- wallet not connected with staking dapp

**Reproduction steps:**
1. Go to staking "Home" page (https://dev.staking.synthetix.io/)
2. Click on "Switch to L2" button
3. Confirm request to add new network in metamask
4. Confirm request to switch to new network in metamask

**Current behavior:**
- after confirming requests in metamask, nothing happens in the dapp
- if you click on "Switch to L2" button again, you will see "Network not supported on Layer 2" error (which is not true because you're already on "optimism mainnet" network in metamask)
- if you refresh the page, everything works as it should ("Switch to L2" button is gone)

**Expected behavior:**
- User should be properly switched to L2 network.
- "Switch to L2" button should disappear.

**Screenshots:**
![2021-03-23 16 06 26](https://user-images.githubusercontent.com/8177587/112173572-fba3da80-8bf5-11eb-8eaa-b92a1addd069.gif)
<img width="327" alt="Screenshot 2021-03-23 at 16 25 10" src="https://user-images.githubusercontent.com/8177587/112171694-59cfbe00-8bf4-11eb-8244-d36b6e9d344e.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2.2
 - Browser: Chrome 89.0.4389.95

**Comment by clementbalestrat** [comment]
Good find. It's actually an issue for L1 as well. When you disconnect a wallet it kinda messes things up.
