### ISSUE TITLE
Several browser console errors are being thrown after switching from L1 to L2

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/staking#421]
**Description:**
Several browser console errors are being thrown after switching from L1 to L2.

**Prerequisites:**
- connected to L1 mainnet in metamask
- wallet not connected with staking dapp

**Reproduction steps:**
1. Go to staking "Home" page (https://dev.staking.synthetix.io/)
2. Connect your wallet with dapp
3. Click on "Switch to L2" button
4. Wait for several seconds (~10 sec)

**Current behavior:**
- after switching to L2, there are several browser console errors being thrown

**Expected behavior:**
- there shouldn't be any errors after switching networks

**Screenshots:**
![2021-03-23 16 38 18](https://user-images.githubusercontent.com/8177587/112174146-753bc880-8bf6-11eb-871d-cb0d4d708838.gif)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2.2
 - Browser: Chrome 89.0.4389.95

**Comment by clementbalestrat** [comment]
Yeah so this one is a bit tricky. `ethers.js` double checks the network for every call using `getNetwork()` and throws an error if the current network is different than the one passed in the params. So it will happen when we switch the network when the dApp is doing web3 calls in the background.

I'm going to ignore this for now as it's happening on L1 to (switching from Mainnet to Kovan for example).

**Comment by drptbl** [comment]
@clementbalestrat @andytcf what is the reason for closing it if it's not fixed?

<img width="1648" alt="Screenshot 2021-04-07 at 09 07 35" src="https://user-images.githubusercontent.com/8177587/113824969-b4ceec80-9780-11eb-83e2-e5425155f82e.png">
