### ISSUE TITLE
"Est. APR" for SNX pool has wrong calculations for a while after changing networks between L1 and L2 networks

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/staking#422]
**Description:**
"Est. APR" for SNX pool has wrong calculations for a while after changing networks between L1 and L2 networks.

**Reproduction steps:**
1. Go to staking "Earn" page (https://dev.staking.synthetix.io/earn)
2. Connect your wallet with dapp
3. Take a look at "Est. APR" for SNX pool (on top of the page and on the "Earn" list) and remember the numbers
4. Click on "Switch to L2" button and immediately look at "Est. APR" for SNX pool (on top of the page and on the "Earn" list)

**Current behavior:**
- after switching networks (from L1 to L2 or from L2 to L1), calculations for "Est. APR" are wrong for SNX pool

**Expected behavior:**
- only proper calculations should be shown

**Screenshots:**
![2021-03-23 16 44 53](https://user-images.githubusercontent.com/8177587/112176534-77068b80-8bf8-11eb-9a4d-1a31b67c06ce.gif)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2.2
 - Browser: Chrome 89.0.4389.95

**Comment by clementbalestrat** [comment]
Ok it's because when a wallet is not staking, it defaults to the top 1000 holder average. Problem is, it's taking the data from the graph a.k.a Layer 1.

For now I will just return 0 if wallet isn't staking and network is L2.

**Comment by drptbl** [comment]
@clementbalestrat @andytcf what is the reason for closing it if it's not fixed?
