### ISSUE TITLE
dApp doesn't change network if it's changed when wallet is not connected

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/staking#452]
**Description:**
dApp doesn't change network if it's changed when wallet is not connected.

**Prerequisites:**
Wallet is not connected.

**Reproduction steps:**
1. Go to staking "Home" page (https://dev.staking.synthetix.io/)
2. Change network in metamask to L2

**Current behavior:**
- dApp doesn't seem to be changing it's network until your wallet is connected.

**Expected behavior:**
- dApp should change its network even without connecting a wallet.

**Screenshots:**
![2021-03-30 22 50 40](https://user-images.githubusercontent.com/8177587/113056320-f02f5100-91ab-11eb-9d4c-d352b28ec67f.gif)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2.2
 - Browser: Chrome 89.0.4389.95

**Comment by clementbalestrat** [comment]
I will leave that one for later. I don't want to change too much logic before the release.
