### ISSUE TITLE
Make it more clear for users that they can't use other wallets than metamask for L2

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/staking#455]
**Description:**
Make it more clear for users that they can't use other wallets than metamask for L2. Options related to L2 should be dimmed out in case someone uses different wallet method than metamask with some information that metamask is the only wallet supported for L2 on "Layer 2" page.

For example here:
<img width="1104" alt="Screenshot 2021-03-31 at 18 07 08" src="https://user-images.githubusercontent.com/8177587/113175751-0ab90700-924c-11eb-81ee-5b93f2bc1f14.png">

**Comment by Boda805** [comment]
I'd like to take an attempt at this if no-one else minds.

**Comment by JChiaramonte7** [comment]
@drptbl is what we have now sufficient? it doesn't block users without a metamask wallet, but there's a pretty strong disclaimer

![image](https://user-images.githubusercontent.com/4015977/116474609-b9019d80-a846-11eb-9aca-55366d160f86.png)
