### ISSUE TITLE
[L2] Add support for Brave wallet

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/staking#465]
**Description:**
Add support for Brave wallet.

**Prerequisites:**
- Brave wallet

**Reproduction steps:**
1. Go to staking "Home" page (https://staking.synthetix.io/)
2. Connect Brave wallet with "MetaMask" login method
3. Click on "Switch to L2" button

**Current behavior:**
- Brave wallet doesn't work on L2 with staking dapp.

**Expected behavior:**
- Brave wallet should work on L2 with staking dapp.

**Screenshots:**
<img width="374" alt="Screenshot 2021-04-07 at 18 25 49" src="https://user-images.githubusercontent.com/8177587/113900992-b45d4280-97ce-11eb-9ed8-d8ccc5800762.png">
![2021-04-07 18 19 25](https://user-images.githubusercontent.com/8177587/113900661-5b8daa00-97ce-11eb-9723-814799305c35.gif)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2.2
 - Browser: Brave Version 1.22.71 Chromium: 89.0.4389.114 (Official Build) (x86_64)

**Comment by clementbalestrat** [comment]
@drptbl closing that one
