### ISSUE TITLE
Browser wallet method has no additional details if there is no browser wallet present, "Install Browser Wallet" button doesn't work

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/staking#478]
**Description:**
Browser wallet method has no additional details if there is no browser wallet present, "Install Browser Wallet" button doesn't work.

**Prerequisites:**
No browser wallet available.

**Reproduction steps:**
1. Go to staking "Home" page (https://staking-git-feat-browser-wallet-synthetixio.vercel.app/)
2. Click on "Connect wallet" button
3. Click on "Browser Wallet" method

**Current behavior:**
- there is no description if no browser wallet is available
- "Install Browser Wallet" button doesn't work

**Expected behavior:**
- description should be available to guide user on what to do
- "Install Browser Wallet" button should work

**Screenshots:**
<img width="1281" alt="Screenshot 2021-04-13 at 21 25 15" src="https://user-images.githubusercontent.com/8177587/114609328-f559c900-9c9e-11eb-82c1-ded5a2288f56.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2.2
 - Browser: Brave Version 1.22.71 Chromium: 89.0.4389.114 (Official Build) (x86_64)

**Comment by clementbalestrat** [comment]
@drptbl closing that one
