### ISSUE TITLE
Broken zapper tokenlist

### ISSUE THREAD

**Issue by vbstreetz** [Synthetixio/staking#551]
**Describe the bug**
Some icons not loading up.

**To Reproduce**
1. Visit dapp
2. Open dev console
3. Expect to see a bunch of icon load 404s.

**Expected behavior**
Images should load.

**Screenshots**
![](https://user-images.githubusercontent.com/8177587/119278983-211a8800-bc29-11eb-97aa-05001192d83c.png)

**Comment by andytcf** [comment]
@vbstreetz fixing this in this PR https://github.com/Synthetixio/staking/pull/562
