### ISSUE TITLE
"Invalid BigNumber Value" when claiming staking rewards

### ISSUE THREAD

**Issue by khbrosnan** [Synthetixio/staking#558]
**Describe the bug**
The staking app says "Invalid BigNumber Value (Argument="Value", Value=Undefined, Code=INVALID_ARGUMENT, Version=Bignumber/5.0.13)" where the fee estimate should be for claiming my staked SNX, and if you click claim anyways then it says "An unexpected error occurred." at the bottom of the window. It's been like this since the fee got low enough to finally claim my rewards. I reproduced the bug in all browsers(Chrome, Brave, Internet Explorer, Edge, Firefox)

**To Reproduce**
1. Go to claim staking rewards for SNX using Argent Wallet and walletconnect. 
2. See that it says "Invalid BigNumber Value (Argument="Value", Value=Undefined, Code=INVALID_ARGUMENT, Version=Bignumber/5.0.13)" instead of a fee estimate
3. Click the claim rewards button
4. See  "An unexpected error occurred." and no chance to execute a transaction.

**Expected behavior**
Me getting a fee estimate when I go to claim my rewards, and then actually being able to claim them. The epoch will end and my stake will be lost

**Desktop:**
 - OS: Windows10
 - Browser [Brave, Firefox, 

**Smartphone:**
 - Device: Iphone SE2
 - OS: IOS 14.6
 - Argent Wallet with Walletconnect
![staking fee not calculating](https://user-images.githubusercontent.com/37989976/120103951-c6e16180-c117-11eb-9bd9-e1e316c1beb3.png)
![staking messed up 2](https://user-images.githubusercontent.com/37989976/120103987-deb8e580-c117-11eb-93b2-5cfe7ca56fb9.png)

**Comment by andytcf** [comment]
@khbrosnan are you still experiencing this issue?

**Comment by fritzschoff** [comment]
It seems that this happens as well on L2 because of the gas price is getting incorrectly calculated

**Comment by fritzschoff** [comment]
should be fixed by now from the new release of the staking app and the refactoring from 0xClem about gas calculation
