### ISSUE TITLE
Metamask prompts to authorize the transaction is not showing

### ISSUE THREAD

**Issue by lpellegr** [Synthetixio/staking#594]
**Describe the bug**

While using staking.synthetix.io this week to claim my stacking rewards, I am encountering the following issue when I am trying to burn my sUSD to 1000% in order to fix my c-ratio.

The issue is that when I click the button to confirm the burn, a "Confirm Transaction" popup appears but the Metamask prompts that used to appear is not displayed, thus preventing me to fix my c-ratio and claim my SNX rewards among others.

**To Reproduce**
1. Go to https://staking.synthetix.io/
2. Connect your Metamask wallet using the Browser Wallet option. Note that my wallet is on L2 and the Metamask prompt to connect is working fine.
3. Once connected, click "Burn to 1000%" on the home page.
4. This opens the Burn tab. Click again on the "Burn to 1000%" option.
5. A page that summarizes the number of sUSD to burn appears. Click on "Burn sUSD".
6. A popup to confirm the transaction appears. It contains the message "Follow the Metamask prompts to authorize the transaction". Unfortunately, the prompt is not displayed.

**Expected behavior**
I expect the Metamask prompts to appear so that I can confirm the transaction.

**Screenshots**

![Screenshot from 2021-06-23 09-36-43](https://user-images.githubusercontent.com/128898/123055876-a058d280-d406-11eb-8a92-e2a55a2578b4.png)

**Desktop:**
 - OS: Fedora 33
 - Browser: Chrome 91.0.4472.101

**Additional context**

Metamask is allowed to execute on https://staking.synthetix.io. I am using version 9.6.1 of Metamask.

Everything was working fine last week.

My current c-ratio is 726.24%

**Comment by clementbalestrat** [comment]
hey @lpellegr, did you connect a hardware wallet to Metamask?

**Comment by lpellegr** [comment]
@clementbalestrat No. However, I just retried and it is now working. It was most probably linked with the L2 maintenance from Yesterday.
